server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: 54455357342478364763268483726487236482638746283764832
